# Generated by Django 5.1.4 on 2025-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Add an emoji like 🏅, 🔬, 🎭', max_length=10)),
            ],
        ),
    ]
