# Generated by Django 5.1.4 on 2025-06-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
